name: riloi_web
description: リロイと申します。学生ボカロP ご依頼・ご連絡はcontact@riloi.comまで

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  http: ^0.13.5
  fluro: ^2.0.4
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/video/
    - lib/assets/discography/
